# TCL File Generated by Component Editor 13.1
# Tue Jun 14 09:50:21 IST 2016
# DO NOT MODIFY



# +-----------------------------------
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module sd_host_controller
# | 
set_module_property DESCRIPTION "SD/SDIO Host Controller"
set_module_property NAME sd_host_controller
set_module_property VERSION 1.14
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SLS/Memory
set_module_property AUTHOR "System Level Solutions"
set_module_property ICON_PATH sls_logo.jpg
set_module_property DISPLAY_NAME "SD/SDIO Host Controller"
#set_module_property TOP_LEVEL_HDL_FILE hdl/sls_sdhc_top.v
#set_module_property TOP_LEVEL_HDL_MODULE sls_sdhc_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
# | 
# +-----------------------------------

# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL sls_sdhc_top
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sls_sdhc_top.v VERILOG PATH hdl/sls_sdhc_top.v TOP_LEVEL_FILE
add_fileset_file sls_sdhc_tx_fifo.v VERILOG PATH hdl/sls_sdhc_tx_fifo.v
add_fileset_file sls_sdhc_rx_fifo.v VERILOG PATH hdl/sls_sdhc_rx_fifo.v
add_fileset_file sls_sdhc_top.ocp OTHER PATH hdl/sls_sdhc_top.ocp

# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter tx_buffer_depth INTEGER 256
set_parameter_property tx_buffer_depth DEFAULT_VALUE 256
set_parameter_property tx_buffer_depth DISPLAY_NAME tx_buffer_depth
set_parameter_property tx_buffer_depth UNITS None
set_parameter_property tx_buffer_depth ALLOWED_RANGES {128 256 512 1024 2048 }
set_parameter_property tx_buffer_depth DISPLAY_HINT ""
set_parameter_property tx_buffer_depth AFFECTS_GENERATION false
set_parameter_property tx_buffer_depth HDL_PARAMETER true
add_parameter tx_buffer_add INTEGER 8
set_parameter_property tx_buffer_add DEFAULT_VALUE 8
set_parameter_property tx_buffer_add DISPLAY_NAME "Transmit data buffer address width"
set_parameter_property tx_buffer_add DERIVED true
set_parameter_property tx_buffer_add UNITS None
set_parameter_property tx_buffer_add ALLOWED_RANGES -2147483648:2147483647
set_parameter_property tx_buffer_add DISPLAY_HINT ""
set_parameter_property tx_buffer_add AFFECTS_GENERATION false
set_parameter_property tx_buffer_add HDL_PARAMETER true
add_parameter rx_buffer_depth INTEGER 256
set_parameter_property rx_buffer_depth DEFAULT_VALUE 256
set_parameter_property rx_buffer_depth DISPLAY_NAME rx_buffer_depth
set_parameter_property rx_buffer_depth UNITS None
set_parameter_property rx_buffer_depth ALLOWED_RANGES {128 256 512 1024 2048 }
set_parameter_property rx_buffer_depth DISPLAY_HINT ""
set_parameter_property rx_buffer_depth AFFECTS_GENERATION false
set_parameter_property rx_buffer_depth HDL_PARAMETER true
add_parameter rx_buffer_add INTEGER 8
set_parameter_property rx_buffer_add DEFAULT_VALUE 8
set_parameter_property rx_buffer_add DISPLAY_NAME "Receive data buffer address width"
set_parameter_property rx_buffer_add DERIVED true
set_parameter_property rx_buffer_add UNITS None
set_parameter_property rx_buffer_add ALLOWED_RANGES -2147483648:2147483647
set_parameter_property rx_buffer_add DISPLAY_HINT ""
set_parameter_property rx_buffer_add AFFECTS_GENERATION false
set_parameter_property rx_buffer_add HDL_PARAMETER true
# | 
# +-----------------------------------


set_module_property VALIDATION_CALLBACK my_validate_callback
proc my_validate_callback {} {
  
  set tx_add_width [get_parameter_value tx_buffer_depth ]
  set rx_add_width [get_parameter_value rx_buffer_depth ]
  
  if {$tx_add_width == 128} {
  	set_parameter_value tx_buffer_add 7
  	send_message " info" "Transmit data buffer size is 512 Bytes"
  }	
  if {$tx_add_width == 256} {
  	set_parameter_value tx_buffer_add 8
  	send_message " info" "Transmit data buffer size is 1 KBytes"
  }	
  if {$tx_add_width == 512} {
  	set_parameter_value tx_buffer_add 9
  	send_message " info" "Transmit data buffer size is 2 KBytes"
  }
  if {$tx_add_width == 1024} {
  	set_parameter_value tx_buffer_add 10
  	send_message " info" "Transmit data buffer size is 4 KBytes"
  }
  if {$tx_add_width == 2048} {
  	set_parameter_value tx_buffer_add 11
  	send_message " info" "Transmit data buffer size is 8 KBytes"
  }
  

  if {$rx_add_width == 128} {
  	set_parameter_value rx_buffer_add 7
  	send_message " info" "Receive data buffer size is 512 Bytes"
  }	
  if {$rx_add_width == 256} {
  	set_parameter_value rx_buffer_add 8
  	send_message " info" "Receive data buffer size is 1 KBytes"
  }	
  if {$rx_add_width == 512} {
  	set_parameter_value rx_buffer_add 9
  	send_message " info" "Receive data buffer size is 2 KBytes"
  }
  if {$rx_add_width == 1024} {
  	set_parameter_value rx_buffer_add 10
  	send_message " info" "Receive data buffer size is 4 KBytes"
  }
  if {$rx_add_width == 2048} {
  	set_parameter_value rx_buffer_add 11
  	send_message " info" "Receive data buffer size is 8 KBytes"
  }  

}


# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq0
# | 
add_interface irq0 interrupt end
set_interface_property irq0 associatedAddressablePoint AvS
set_interface_property irq0 associatedClock clock
set_interface_property irq0 associatedReset reset

set_interface_property irq0 ENABLED true

add_interface_port irq0 AvS_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dma_write
# | 
add_interface dma_write avalon start
set_interface_property dma_write addressUnits SYMBOLS
set_interface_property dma_write associatedClock clock
set_interface_property dma_write associatedReset reset
set_interface_property dma_write burstOnBurstBoundariesOnly false
set_interface_property dma_write doStreamReads false
set_interface_property dma_write doStreamWrites false
set_interface_property dma_write linewrapBursts false
set_interface_property dma_write readLatency 0

set_interface_property dma_write ENABLED true

add_interface_port dma_write AvM_wr_address address Output 32
add_interface_port dma_write AvM_wr_writedata writedata Output 32
add_interface_port dma_write AvM_wr_write_n write_n Output 1
add_interface_port dma_write AvM_wr_chipselect chipselect Output 1
add_interface_port dma_write AvM_wr_waitrequest waitrequest Input 1
add_interface_port dma_write AvM_wr_byteenable byteenable Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dma_read
# | 
add_interface dma_read avalon start
set_interface_property dma_read addressUnits SYMBOLS
set_interface_property dma_read associatedClock clock
set_interface_property dma_read associatedReset reset
set_interface_property dma_read burstOnBurstBoundariesOnly false
set_interface_property dma_read doStreamReads false
set_interface_property dma_read doStreamWrites false
set_interface_property dma_read linewrapBursts false
set_interface_property dma_read readLatency 0

set_interface_property dma_read ENABLED true

add_interface_port dma_read AvM_rd_address address Output 32
add_interface_port dma_read AvM_rd_read_n read_n Output 1
add_interface_port dma_read AvM_rd_readdata readdata Input 32
add_interface_port dma_read AvM_rd_waitrequest waitrequest Input 1
add_interface_port dma_read AvM_rd_readdatavalid readdatavalid Input 1
add_interface_port dma_read AvM_rd_byteenable byteenable Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point bd_read
# | 
add_interface bd_read avalon start
set_interface_property bd_read addressUnits SYMBOLS
set_interface_property bd_read associatedClock clock
set_interface_property bd_read associatedReset reset
set_interface_property bd_read burstOnBurstBoundariesOnly false
set_interface_property bd_read doStreamReads false
set_interface_property bd_read doStreamWrites false
set_interface_property bd_read linewrapBursts false
set_interface_property bd_read readLatency 0

set_interface_property bd_read ENABLED true

add_interface_port bd_read AvM_bd_waitrequest waitrequest Input 1
add_interface_port bd_read AvM_bd_read_n read_n Output 1
add_interface_port bd_read AvM_bd_readdatavalid readdatavalid Input 1
add_interface_port bd_read AvM_bd_readaddress address Output 32
add_interface_port bd_read AvM_bd_readdata readdata Input 32
add_interface_port bd_read AvM_bd_byteenable byteenable Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AvS
# | 
add_interface AvS avalon end
set_interface_property AvS addressUnits WORDS
set_interface_property AvS associatedClock clock
set_interface_property AvS associatedReset reset
set_interface_property AvS bitsPerSymbol 8
set_interface_property AvS burstOnBurstBoundariesOnly false
set_interface_property AvS burstcountUnits WORDS
set_interface_property AvS explicitAddressSpan 0
set_interface_property AvS holdTime 0
set_interface_property AvS linewrapBursts false
set_interface_property AvS maximumPendingReadTransactions 0
set_interface_property AvS readLatency 0
set_interface_property AvS readWaitTime 1
set_interface_property AvS setupTime 0
set_interface_property AvS timingUnits Cycles
set_interface_property AvS writeWaitTime 0
set_interface_property AvS ENABLED true
set_interface_property AvS EXPORT_OF ""
set_interface_property AvS PORT_NAME_MAP ""
set_interface_property AvS CMSIS_SVD_VARIABLES ""
set_interface_property AvS SVD_ADDRESS_GROUP ""

add_interface_port AvS AvS_address address Input 8
add_interface_port AvS AvS_chipselect chipselect Input 1
add_interface_port AvS AvS_write_n write_n Input 1
add_interface_port AvS AvS_read_n read_n Input 1
add_interface_port AvS AvS_writedata writedata Input 32
add_interface_port AvS AvS_byteenable byteenable Input 4
add_interface_port AvS AvS_readdata readdata Output 32
add_interface_port AvS AvS_waitrequest waitrequest Output 1
set_interface_assignment AvS embeddedsw.configuration.isFlash 0
set_interface_assignment AvS embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AvS embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AvS embeddedsw.configuration.isPrintableDevice 0
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end SD_CMD_i export Input 1
add_interface_port conduit_end SD_DAT0_i export Input 1
add_interface_port conduit_end SD_DAT1_i export Input 1
add_interface_port conduit_end SD_DAT2_i export Input 1
add_interface_port conduit_end SD_DAT3_i export Input 1
add_interface_port conduit_end SD_In export Input 1
add_interface_port conduit_end SD_Wp export Input 1
add_interface_port conduit_end SD_Busy export Output 1
add_interface_port conduit_end SD_CLK_o export Output 1
add_interface_port conduit_end SD_CMD_o export Output 1
add_interface_port conduit_end SD_DAT0_o export Output 1
add_interface_port conduit_end SD_DAT1_o export Output 1
add_interface_port conduit_end SD_DAT2_o export Output 1
add_interface_port conduit_end SD_DAT3_o export Output 1
add_interface_port conduit_end SD_CMD_oe_o export Output 1
add_interface_port conduit_end SD_DATA_oe_o export Output 1

# | 
# +-----------------------------------

# | 
# +-----------------------------------
# | Device tree generation
# |
set_module_assignment embeddedsw.dts.compatible "sls,sdio-cntrlr"
set_module_assignment embeddedsw.dts.group "mmc"
set_module_assignment embeddedsw.dts.name "sls_sdio"
set_module_assignment embeddedsw.dts.vendor "SLS"
# |
# +-----------------------------------
